[env]
# https://android.googlesource.com/platform/external/jemalloc_new/+/refs/heads/master/TUNING.md
JEMALLOC_SYS_WITH_MALLOC_CONF = "percpu_arena:percpu,oversize_threshold:0,background_thread:true,dirty_decay_ms:5000,muzzy_decay_ms:5000"

## If you are using aarch64-apple-darwin, you may need to set the following:
## JEMALLOC_SYS_WITH_LG_PAGE = "14"
## JEMALLOC_SYS_WITH_MALLOC_CONF = "oversize_threshold:0,dirty_decay_ms:5000,muzzy_decay_ms:5000"

[source.crates-io]
replace-with = 'ustc' # 指定使用下面哪个源，修改为source.后面的内容即可
#阿里云
[source.aliyun]
registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"
# 中国科学技术大学
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"
# 上海交通大学
[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"
# 清华大学
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
# rustcc社区
[source.rustcc]
registry = "https://code.aliyun.com/rustcc/crates.io-index.git"
