name: "Test Stateless Cluster Linux"
description: "Running stateless tests in cluster mode"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test

    - name: Test setup
      shell: bash
      run: |
        bash ./scripts/setup/dev_setup.sh -yd

    - name: Start UDF Server
      shell: bash
      run: |
        docker run -d --name minio -p 9000:9000 -p 9001:9001 -e MINIO_ROOT_USER=minioadmin -e MINIO_ROOT_PASSWORD=minioadmin quay.io/minio/minio server /data --console-address ":9001"
        pip install databend-udf>=0.2.7
        python3 tests/udf/udf_server.py &
        sleep 2

    - name: Run Stateless Tests with Cluster mode
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-stateless-tests-cluster.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-stateless-cluster-linux
